version: '2'
services:
  web:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: expressjs-angular-base
    environment:
      - WEB_PORT=8080
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - ../:/code
